services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
    ports:
      - "5555:5555"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
